<?php 
Redux::setSection( $opt_name, array(
    'title'            => __( 'Accessibility', 'solar' ),
    'id'               => 'tvlgiao_wpdance_accessibility',
    'desc'             => __( '', 'solar' ),
    'customizer_width' => '400px',
    'icon'             => 'el el-wrench-alt',
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Breadcrumb', 'solar' ),
    'id'               => 'tvlgiao_wpdance_breadcrumb',
    'desc'             => __( '', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        /******************************** BREADCRUMB GENERAL *******************************/
        array(
           'id'       => 'tvlgiao_wpdance_breadcrumb_general_section_start',
            'type'     => 'section',
            'title'    => __( 'General', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'indent'   => true,
        ),

        /****************************/
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_type',
                'type'     => 'radio',
                'title'    => __( 'Select The Layout', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['type'],
                'default'  => $wd_default_data['breadcrumb']['default']['type'],
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_background_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Background Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['bg_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['bg_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_type', '=', 'breadcrumb_default'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_background',
                'type'     => 'media',
                'url'      => true,
                'title'    => __( 'Background', 'solar' ),
                'compiler' => 'true',
                'desc'     => __( '', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => array('url'  => $wd_default_data['breadcrumb']['default']['background']),
                'required' => array('tvlgiao_wpdance_breadcrumb_type', '=', 'breadcrumb_banner'),
            ),
            array(
                'id'             => 'tvlgiao_wpdance_breadcrumb_height',
                'type'           => 'dimensions',
                'units'          => false,    // You can specify a unit value. Possible: px, em, %
                'width'          => false,   
                'units_extended' => 'true',  // Allow users to select any type of unit
                'title'          => __( 'Height', 'solar' ),
                'subtitle'       => __( '', 'solar' ),
                'desc'           => __( 'Unit: pixels', 'solar' ),
                'default'        => array('height' => $wd_default_data['breadcrumb']['default']['height']),
                'required' => array('tvlgiao_wpdance_breadcrumb_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_text_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Title & Slug Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['text_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['text_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_text_style',
                'type'     => 'radio',
                'title'    => __( 'Title & Slug Style', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_style'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_style'],
                'required' => array('tvlgiao_wpdance_breadcrumb_type', '!=', 'no_breadcrumb'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_text_align',
                'type'     => 'select',
                'title'    => __( 'Text Align', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_align'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_align'],
                'required' => array('tvlgiao_wpdance_breadcrumb_text_style', '=', 'block'),
            ),
        /****************************/
        array(
            'id'     => 'tvlgiao_wpdance_breadcrumb_general_section_end',
            'type'   => 'section',
            'indent' => false,
        ),
        /******************************** BREADCRUMB ARCHIVE BLOG *******************************/
        array(
           'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_section_start',
            'type'     => 'section',
            'title'    => __( 'Blog Archive', 'solar' ),
            'subtitle' => __( 'Disable this if you want to use the settings in the General section', 'solar' ),
            'indent'   => true,
        ),

        /****************************/
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_customize',
                'type'     => 'switch',
                'title'    => __( 'Customize', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => false,
                'on'       => 'Enable',
                'off'      => 'Disable',
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_type',
                'type'     => 'radio',
                'title'    => __( 'Select The Layout', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['type'],
                'default'  => $wd_default_data['breadcrumb']['default']['type'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_customize', '=', '1'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_background_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Background Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['bg_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['bg_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_type', '=', 'breadcrumb_default'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_background',
                'type'     => 'media',
                'url'      => true,
                'title'    => __( 'Background', 'solar' ),
                'compiler' => 'true',
                'desc'     => __( '', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => array('url'  => $wd_default_data['breadcrumb']['default']['background']),
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_type', '=', 'breadcrumb_banner'),
            ),
            array(
                'id'             => 'tvlgiao_wpdance_breadcrumb_archive_blog_height',
                'type'           => 'dimensions',
                'units'          => false,    // You can specify a unit value. Possible: px, em, %
                'width'          => false,   
                'units_extended' => 'true',  // Allow users to select any type of unit
                'title'          => __( 'Height', 'solar' ),
                'subtitle'       => __( '', 'solar' ),
                'desc'           => __( 'Unit: pixels', 'solar' ),
                'default'        => array('height' => $wd_default_data['breadcrumb']['default']['height']),
                'required'       => array('tvlgiao_wpdance_breadcrumb_archive_blog_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_text_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Title & Slug Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['text_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['text_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_text_style',
                'type'     => 'radio',
                'title'    => __( 'Title & Slug Style', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_style'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_style'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_type', '!=', 'no_breadcrumb'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_blog_text_align',
                'type'     => 'select',
                'title'    => __( 'Text Align', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_align'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_align'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_blog_text_style', '=', 'block'),
            ),
        /****************************/
        array(
            'id'     => 'tvlgiao_wpdance_breadcrumb_archive_blog_section_end',
            'type'   => 'section',
            'indent' => false,
        ),
        /******************************** BREADCRUMB ARCHIVE PRODUCT *******************************/
        array(
           'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_section_start',
            'type'     => 'section',
            'title'    => __( 'Product Archive', 'solar' ),
            'subtitle' => __( 'Use for Product Taxonomy Archive/Product Category. Disable this if you want to use the settings in the General section', 'solar' ),
            'indent'   => true,
        ),

        /****************************/
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_customize',
                'type'     => 'switch',
                'title'    => __( 'Customize', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => false,
                'on'       => 'Enable',
                'off'      => 'Disable',
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_type',
                'type'     => 'radio',
                'title'    => __( 'Select The Layout', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['type'],
                'default'  => $wd_default_data['breadcrumb']['default']['type'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_customize', '=', '1'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_background_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Background Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['bg_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['bg_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_type', '=', 'breadcrumb_default'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_background',
                'type'     => 'media',
                'url'      => true,
                'title'    => __( 'Background', 'solar' ),
                'compiler' => 'true',
                'desc'     => __( '', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => array('url'  => $wd_default_data['breadcrumb']['default']['background']),
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_type', '=', 'breadcrumb_banner'),
            ),
            array(
                'id'             => 'tvlgiao_wpdance_breadcrumb_archive_product_height',
                'type'           => 'dimensions',
                'units'          => false,    // You can specify a unit value. Possible: px, em, %
                'width'          => false,   
                'units_extended' => 'true',  // Allow users to select any type of unit
                'title'          => __( 'Height', 'solar' ),
                'subtitle'       => __( '', 'solar' ),
                'desc'           => __( 'Unit: pixels', 'solar' ),
                'default'        => array('height' => $wd_default_data['breadcrumb']['default']['height']),
                'required'       => array('tvlgiao_wpdance_breadcrumb_archive_product_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_text_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Title & Slug Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['text_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['text_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_text_style',
                'type'     => 'radio',
                'title'    => __( 'Title & Slug Style', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_style'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_style'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_type', '!=', 'no_breadcrumb'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_archive_product_text_align',
                'type'     => 'select',
                'title'    => __( 'Text Align', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_align'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_align'],
                'required' => array('tvlgiao_wpdance_breadcrumb_archive_product_text_style', '=', 'block'),
            ),
        /****************************/
        array(
            'id'     => 'tvlgiao_wpdance_breadcrumb_archive_product_section_end',
            'type'   => 'section',
            'indent' => false,
        ),

        /******************************** WOOCOMMERCE SPECIAL PAGE PAGE *******************************/
        array(
           'id'        => 'tvlgiao_wpdance_breadcrumb_woo_special_page_section_start',
            'type'     => 'section',
            'title'    => __( 'Woocommerce Special Page', 'solar' ),
            'subtitle' => __( 'Use for Cart/Checkout page. Disable this if you want to use the settings in the General section', 'solar' ),
            'indent'   => true,
        ),

        /****************************/
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_customize',
                'type'     => 'switch',
                'title'    => __( 'Customize', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => false,
                'on'       => 'Enable',
                'off'      => 'Disable',
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_type',
                'type'     => 'radio',
                'title'    => __( 'Select The Layout', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['type'],
                'default'  => $wd_default_data['breadcrumb']['default']['type'],
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_customize', '=', '1'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_background_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Background Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['bg_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['bg_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_type', '=', 'breadcrumb_default'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_background',
                'type'     => 'media',
                'url'      => true,
                'title'    => __( 'Background', 'solar' ),
                'compiler' => 'true',
                'desc'     => __( '', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => array('url'  => $wd_default_data['breadcrumb']['default']['background']),
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_type', '=', 'breadcrumb_banner'),
            ),
            array(
                'id'             => 'tvlgiao_wpdance_breadcrumb_woo_special_page_height',
                'type'           => 'dimensions',
                'units'          => false,    // You can specify a unit value. Possible: px, em, %
                'width'          => false,   
                'units_extended' => 'true',  // Allow users to select any type of unit
                'title'          => __( 'Height', 'solar' ),
                'subtitle'       => __( '', 'solar' ),
                'desc'           => __( 'Unit: pixels', 'solar' ),
                'default'        => array('height' => $wd_default_data['breadcrumb']['default']['height']),
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_text_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Title & Slug Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['text_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['text_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_text_style',
                'type'     => 'radio',
                'title'    => __( 'Title & Slug Style', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_style'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_style'],
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_type', '!=', 'no_breadcrumb'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_woo_special_page_text_align',
                'type'     => 'select',
                'title'    => __( 'Text Align', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_align'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_align'],
                'required' => array('tvlgiao_wpdance_breadcrumb_woo_special_page_text_style', '=', 'block'),
            ),
        /****************************/
        array(
            'id'     => 'tvlgiao_wpdance_breadcrumb_woo_special_page_section_end',
            'type'   => 'section',
            'indent' => false,
        ),

        /******************************** SEARCH PAGE *******************************/
        array(
           'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_section_start',
            'type'     => 'section',
            'title'    => __( 'Search Page', 'solar' ),
            'subtitle' => __( 'Disable this if you want to use the settings in the General section', 'solar' ),
            'indent'   => true,
        ),

        /****************************/
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_customize',
                'type'     => 'switch',
                'title'    => __( 'Customize', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => false,
                'on'       => 'Enable',
                'off'      => 'Disable',
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_type',
                'type'     => 'radio',
                'title'    => __( 'Select The Layout', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['type'],
                'default'  => $wd_default_data['breadcrumb']['default']['type'],
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_customize', '=', '1'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_background_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Background Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['bg_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['bg_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_type', '=', 'breadcrumb_default'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_background',
                'type'     => 'media',
                'url'      => true,
                'title'    => __( 'Background', 'solar' ),
                'compiler' => 'true',
                'desc'     => __( '', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'default'  => array('url'  => $wd_default_data['breadcrumb']['default']['background']),
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_type', '=', 'breadcrumb_banner'),
            ),
            array(
                'id'             => 'tvlgiao_wpdance_breadcrumb_search_page_height',
                'type'           => 'dimensions',
                'units'          => false,    // You can specify a unit value. Possible: px, em, %
                'width'          => false,   
                'units_extended' => 'true',  // Allow users to select any type of unit
                'title'          => __( 'Height', 'solar' ),
                'subtitle'       => __( '', 'solar' ),
                'desc'           => __( 'Unit: pixels', 'solar' ),
                'default'        => array('height' => $wd_default_data['breadcrumb']['default']['height']),
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_text_color',
                'type'     => 'color',
                'transparent'=> false,
                'title'    => __( 'Title & Slug Color', 'solar' ),
                'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['breadcrumb']['default']['text_color']),
                'default'  => $wd_default_data['breadcrumb']['default']['text_color'],
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_type', '!=', 'no_breadcrumb'),
            ),
            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_text_style',
                'type'     => 'radio',
                'title'    => __( 'Title & Slug Style', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_style'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_style'],
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_type', '!=', 'no_breadcrumb'),
            ),

            array(
                'id'       => 'tvlgiao_wpdance_breadcrumb_search_page_text_align',
                'type'     => 'select',
                'title'    => __( 'Text Align', 'solar' ),
                'subtitle' => __( '', 'solar' ),
                'desc'     => __( '', 'solar' ),
                'options'  => $wd_default_data['breadcrumb']['choose']['text_align'],
                'default'  => $wd_default_data['breadcrumb']['default']['text_align'],
                'required' => array('tvlgiao_wpdance_breadcrumb_search_page_text_style', '=', 'block'),
            ),
        /****************************/
        array(
            'id'     => 'tvlgiao_wpdance_breadcrumb_search_page_section_end',
            'type'   => 'section',
            'indent' => false,
        ),
    ) 
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Back To Top', 'solar' ),
    'id'               => 'tvlgiao_wpdance_back_to_top',
    'desc'             => __( 'This feature will not show on mobile devices!', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_display',
            'type'     => 'switch',
            'title'    => __( 'Display', 'solar' ),
            'subtitle' => __( 'Enable/Disable scroll button in website.', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['display'],
            'on'       => 'Show',
            'off'      => 'Hide',
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_style',
            'type'     => 'radio',
            'title'    => __( 'Select Style', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'options'  => $wd_default_data['back_to_top']['choose']['style'],
            'default'  => $wd_default_data['back_to_top']['default']['style'],
            'required' => array('tvlgiao_wpdance_back_to_top_display','=','1'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_background_color',
            'type'     => 'color',
            'transparent'=> true,
            'title'    => __( 'Background Color', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['bg_color'],
            'required' => array('tvlgiao_wpdance_back_to_top_style', '=', '0'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_border_color',
            'type'     => 'color_rgba',
            'options'       => array(
                'show_input'                => true,
                'show_initial'              => true,
                'show_alpha'                => true,
                'show_palette'              => true,
                'show_palette_only'         => false,
                'show_selection_palette'    => true,
                'max_palette_size'          => 10,
                'allow_empty'               => true,
                'clickout_fires_change'     => false,
                'choose_text'               => 'Choose',
                'cancel_text'               => 'Cancel',
                'show_buttons'              => true,
                'use_extended_classes'      => true,
                'palette'                   => null,  // show default
                'input_text'                => 'Select Color'
            ),
            'title'    => __( 'Border Color', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['border_color'],
            'required' => array('tvlgiao_wpdance_back_to_top_style', '=', '0'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_background_shape',
            'type'     => 'radio',
            'title'    => __( 'Background Shape', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'options'  => $wd_default_data['back_to_top']['choose']['bg_shape'],
            'default'  => $wd_default_data['back_to_top']['default']['bg_shape'],
            'required' => array('tvlgiao_wpdance_back_to_top_style', '=', '0'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_select_icon',
            'type'     => 'select',
            'data'     => 'elusive-icons',
            'title'    => __( 'Select Icon', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['icon'],
            'required' => array('tvlgiao_wpdance_back_to_top_display','=','1'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_icon_color',
            'type'     => 'color',
            'transparent'=> false,
            'title'    => __( 'Icon Color', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['icon_color'],
            'required' => array('tvlgiao_wpdance_back_to_top_display', '=', '1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_width',
            'type'     => 'text',
            'title'    => __( 'Width', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['width'],
            'required' => array('tvlgiao_wpdance_back_to_top_display', '=', '1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_height',
            'type'     => 'text',
            'title'    => __( 'Height', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['height'],
            'required' => array('tvlgiao_wpdance_back_to_top_display', '=', '1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_right',
            'type'     => 'text',
            'title'    => __( 'Right', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['right'],
            'required' => array('tvlgiao_wpdance_back_to_top_display', '=', '1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_back_to_top_bottom',
            'type'     => 'text',
            'title'    => __( 'Bottom', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['back_to_top']['default']['bottom'],
            'required' => array('tvlgiao_wpdance_back_to_top_display', '=', '1'),
        ),
    ) 
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Visual Effects', 'solar' ),
    'id'               => 'tvlgiao_wpdance_effect',
    'desc'             => __( '', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'tvlgiao_wpdance_loading_effect_display',
            'type'     => 'switch',
            'title'    => __( 'Loading Effect', 'solar' ),
            'subtitle' => __( 'Enable/Disable loading effect in website.', 'solar' ),
            'default'  => $wd_default_data['effects']['default']['loading'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
        ),
        array(
            'id'       => 'tvlgiao_wpdance_sidebar_fixed_effect_display',
            'type'     => 'switch',
            'title'    => __( 'Sidebar Fixed', 'solar' ),
            'subtitle' => __( 'Enable/Disable sidebar fixed effect in website.', 'solar' ),
            'default'  => $wd_default_data['effects']['default']['sidebar_fixed'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
        ),
    ) 
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Email Subscriber Popup', 'solar' ),
    'id'               => 'tvlgiao_wpdance_email_subscriber_popup',
    'desc'             => __( '', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_display',
            'type'     => 'switch',
            'title'    => __( 'Display', 'solar' ),
            'subtitle' => __( 'Enable/Disable email subscriber popup in website.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['display'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_only_home',
            'type'     => 'switch',
            'title'    => __( 'Only Home', 'solar' ),
            'subtitle' => __( 'Enable/Disable email subscriber popup only on homepage.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['only_home'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),

        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_mobile',
            'type'     => 'switch',
            'title'    => __( 'Mobile', 'solar' ),
            'subtitle' => __( 'Enable/Disable email subscriber popup on mobile devices.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['popup_mobile'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_delay_time',
            'type'     => 'text',
            'title'    => __( 'Delay Time', 'solar' ),
            'subtitle' => __( 'Unit: seconds (s)', 'solar' ),
            'desc'     => __( 'Time delay after page load to show popup.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['delay_time'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_session_expire',
            'type'     => 'text',
            'title'    => __( 'Session expire', 'solar' ),
            'subtitle' => __( 'Unit: minutes (m)', 'solar' ),
            'desc'     => __( 'Time does not allow popup display on page (for "Dont show this again" option). Set -1 to forever.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['session_expire'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_banner',
            'type'     => 'media',
            'url'      => true,
            'title'    => __( 'Banner', 'solar' ),
            'compiler' => 'true',
            'desc'     => __( '', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'default'  => '',
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_source',
            'type'     => 'radio',
            'title'    => __( 'Source', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'options'  => $wd_default_data['email_popup']['choose']['source'],
            'default'  => $wd_default_data['email_popup']['default']['source'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_display','=','1'),
        ),

        //Custom content
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_custom_content',
            'type'     => 'editor',
            'title'    => __( 'Custom Content', 'solar' ),
            'subtitle' => __( 'Custom HTML / Shortcode', 'solar' ),
            'desc'     => __( 'You can create a shortcode from the new page creation interface.', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['custom_content'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','custom'),
        ),

        //Feedburner source
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_feedburner_id',
            'type'     => 'text',
            'title'    => __( 'Feedburner ID', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['feedburner_id'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_width',
            'type'     => 'text',
            'title'    => __( 'Width', 'solar' ),
            'subtitle' => __( 'Unit: Pixel', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['width'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_height',
            'type'     => 'text',
            'title'    => __( 'Height', 'solar' ),
            'subtitle' => __( 'Unit: Pixel', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['height'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_title',
            'type'     => 'text',
            'title'    => __( 'Title', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['title'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_desc',
            'type'     => 'text',
            'title'    => __( 'Description', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['desc'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_placeholder',
            'type'     => 'text',
            'title'    => __( 'Placeholder', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['placeholder'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_email_subscriber_popup_button_text',
            'type'     => 'text',
            'title'    => __( 'Button Text', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['email_popup']['default']['button_text'],
            'required' => array('tvlgiao_wpdance_email_subscriber_popup_source','=','feedburner'),
        ),
    ) 
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Facebook Chatbox', 'solar' ),
    'id'               => 'tvlgiao_wpdance_facebook_chatbox',
    'desc'             => __( '', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_display',
            'type'     => 'switch',
            'title'    => __( 'Display', 'solar' ),
            'subtitle' => __( 'Enable/Disable facebook chatbox in website.', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['display'],
            'on'       => 'Enable',
            'off'      => 'Disabled',
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_url',
            'type'     => 'text',
            'title'    => __( 'Fanpage URL', 'solar' ),
            'subtitle' => __( 'Enter your fanpage facebook url...', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['url'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_width',
            'type'     => 'text',
            'title'    => __( 'Width', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['width'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_height',
            'type'     => 'text',
            'title'    => __( 'Height', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['height'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_right',
            'type'     => 'text',
            'title'    => __( 'Right', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['right'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_bottom',
            'type'     => 'text',
            'title'    => __( 'Bottom', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['bottom'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_default_mode',
            'type'     => 'radio',
            'title'    => __( 'Default Layout', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'options'  => $wd_default_data['fb_chatbox']['choose']['default_mode'],
            'default'  => $wd_default_data['fb_chatbox']['default']['default_mode'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_bg_color',
            'type'     => 'color',
            'transparent'=> false,
            'title'    => __( 'Background Color', 'solar' ),
            'subtitle' => sprintf(__( '(Default: %s).', 'solar' ), $wd_default_data['fb_chatbox']['default']['bg_color']),
            'default'  => $wd_default_data['fb_chatbox']['default']['bg_color'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_logo',
            'type'     => 'media',
            'url'      => true,
            'title'    => __( 'Logo', 'solar' ),
            'compiler' => 'true',
            'desc'     => __( '', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'default'  => array( 'url' => $wd_default_data['fb_chatbox']['default']['logo'] ),
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_text_footer',
            'type'     => 'text',
            'title'    => __( 'Text Footer', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( 'Text displays when the chatbox window is hidden', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['text_footer'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_link_caption',
            'type'     => 'text',
            'title'    => __( 'Link Caption', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['link_caption'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
        array(
            'id'       => 'tvlgiao_wpdance_facebook_chatbox_link_url',
            'type'     => 'text',
            'title'    => __( 'Link URL', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['fb_chatbox']['default']['link_url'],
            'required' => array('tvlgiao_wpdance_facebook_chatbox_display','=','1'),
        ),
    ) 
) );

Redux::setSection( $opt_name, array(
    'title'            => __( 'Social Share', 'solar' ),
    'id'               => 'tvlgiao_wpdance_share_button',
    'desc'             => __( '', 'solar' ),
    'subsection'       => true,
    'customizer_width' => '400px',
    'fields'     => array(
        array(
            'id'       => 'tvlgiao_wpdance_share_button_display',
            'type'     => 'switch',
            'title'    => __( 'Display', 'solar' ),
            'subtitle' => __( 'Enable/Disable all social share button in website.', 'solar' ),
            'default'  => $wd_default_data['social_share']['default']['display'],
            'on'       => 'Show',
            'off'      => 'Hide',
        ),

        array(
            'id'       => 'tvlgiao_wpdance_share_button_custom_pubid',
            'type'     => 'text',
            'title'    => __( 'Addthis Profile ID', 'solar' ),
            'subtitle' => __( '', 'solar' ),
            'desc'     => __( '', 'solar' ),
            'default'  => $wd_default_data['social_share']['default']['pubid'],
            'required' => array('tvlgiao_wpdance_share_button_display','=','1'),
        ),
        
    ) 
) );
?>